/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 19-Jun-2021 4:45:15 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */
--CREATE DATABASE TT_TinHoc
USE [TT_TinHoc]
GO
/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DangKy_HoaDon]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DangKy] DROP CONSTRAINT [FK_DangKy_HoaDon]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DangKy_HocVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DangKy] DROP CONSTRAINT [FK_DangKy_HocVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DangKy_Lop]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DangKy] DROP CONSTRAINT [FK_DangKy_Lop]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDon_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDon] DROP CONSTRAINT [FK_HoaDon_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_LichSuThi_DangKy]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [LichSuThi] DROP CONSTRAINT [FK_LichSuThi_DangKy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_LichSuTotNghiep_ChungChi]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [LichSuTotNghiep] DROP CONSTRAINT [FK_LichSuTotNghiep_ChungChi]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_LichSuTotNghiep_HocVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [LichSuTotNghiep] DROP CONSTRAINT [FK_LichSuTotNghiep_HocVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Lop_MonHoc]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Lop] DROP CONSTRAINT [FK_Lop_MonHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Lop_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Lop] DROP CONSTRAINT [FK_Lop_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MonHoc_NhomMonHoc]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MonHoc] DROP CONSTRAINT [FK_MonHoc_NhomMonHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_NhomMonHoc_ChungChi]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [NhomMonHoc] DROP CONSTRAINT [FK_NhomMonHoc_ChungChi]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ChungChi]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ChungChi]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DangKy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DangKy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HoaDon]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HoaDon]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HocVien]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HocVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[LichSuThi]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [LichSuThi]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[LichSuTotNghiep]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [LichSuTotNghiep]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Lop]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Lop]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MonHoc]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MonHoc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NhanVien]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NhomMonHoc]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NhomMonHoc]
GO

/* Create Tables */

CREATE TABLE [ChungChi]
(
	[MaChungChi] char(8) NOT NULL,
	[TenChungChi] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [DangKy]
(
	[NgayDangKy] varchar(50) NOT NULL,
	[MaHV] char(8) NOT NULL,
	[MaLop] char(8) NOT NULL,
	[MaHD] char(8) NULL
)
GO

CREATE TABLE [HoaDon]
(
	[MaHD] char(8) NOT NULL,
	[NgayLapHD] date NOT NULL,
	[TongTien] money NOT NULL,
	[MaNV] char(8) NOT NULL
)
GO

CREATE TABLE [HocVien]
(
	[MaHV] char(8) NOT NULL,
	[Password] varchar(20) NOT NULL,
	[HoTen] nvarchar(50) NOT NULL,
	[CCCD] char(12) NOT NULL,
	[Email] varchar(50) NOT NULL,
	[SDT] char(10) NOT NULL,
	[NgaySinh] date NULL
)
GO

CREATE TABLE [LichSuThi]
(
	[MaHV] char(8) NOT NULL,
	[MaLop] char(8) NOT NULL,
	[NgayThi] datetime NOT NULL,
	[DiaDiem] varchar(50) NULL,
	[Diem] float NOT NULL DEFAULT 0.0
)
GO

CREATE TABLE [LichSuTotNghiep]
(
	[NgayNhan] date NOT NULL,
	[MaHV] char(8) NOT NULL,
	[MaChungChi] char(8) NOT NULL
)
GO

CREATE TABLE [Lop]
(
	[MaLop] char(8) NOT NULL,
	[NgayMo] date NOT NULL,
	[Soluong] int NOT NULL DEFAULT 20,
	[MaMH] char(8) NOT NULL,
	[HocPhi] money NOT NULL DEFAULT 200000,
	[MaNV] char(8) NULL
)
GO

CREATE TABLE [MonHoc]
(
	[MaMH] char(8) NOT NULL,
	[TenMH] nvarchar(50) NOT NULL,
	[MaNhomMH] char(8) NULL
)
GO

CREATE TABLE [NhanVien]
(
	[MaNV] char(8) NOT NULL,
	[Password] varchar(20) NOT NULL,
	[HoTen] nvarchar(50) NOT NULL,
	[Email] varchar(50) NOT NULL,
	[CCCD] char(12) NOT NULL,
	[NgaySinh] date NULL,
	[SDT] char(10) NOT NULL,
	[Luong] money NULL DEFAULT 5000000,
	[Role] nvarchar(20) NOT NULL
)
GO

CREATE TABLE [NhomMonHoc]
(
	[MaNhomMH] char(8) NOT NULL,
	[TenNhomMH] nvarchar(30) NOT NULL,
	[MaChungChi] char(8) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [ChungChi] 
 ADD CONSTRAINT [PK_ChungChi]
	PRIMARY KEY CLUSTERED ([MaChungChi] ASC)
GO

ALTER TABLE [DangKy] 
 ADD CONSTRAINT [PK_DangKy]
	PRIMARY KEY CLUSTERED ([MaHV] ASC,[MaLop] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DangKy_HoaDon] 
 ON [DangKy] ([MaHD] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DangKy_HocVien] 
 ON [DangKy] ([MaHV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DangKy_Lop] 
 ON [DangKy] ([MaLop] ASC)
GO

ALTER TABLE [HoaDon] 
 ADD CONSTRAINT [PK_HoaDon]
	PRIMARY KEY CLUSTERED ([MaHD] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDon_NhanVien] 
 ON [HoaDon] ([MaNV] ASC)
GO

ALTER TABLE [HocVien] 
 ADD CONSTRAINT [PK_HocVien]
	PRIMARY KEY CLUSTERED ([MaHV] ASC)
GO

ALTER TABLE [HocVien] 
 ADD CONSTRAINT [Uni_CCCD] UNIQUE NONCLUSTERED ([CCCD] ASC)
GO

ALTER TABLE [LichSuThi] 
 ADD CONSTRAINT [PK_LichSuThi]
	PRIMARY KEY CLUSTERED ([MaHV] ASC,[MaLop] ASC,[NgayThi] ASC)
GO

ALTER TABLE [LichSuThi] 
 ADD CONSTRAINT [C_Diem] CHECK (Diem>=0.0 and Diem<=10.0
)
GO

CREATE NONCLUSTERED INDEX [IXFK_LichSuThi_DangKy] 
 ON [LichSuThi] ([MaHV] ASC,[MaLop] ASC)
GO

ALTER TABLE [LichSuTotNghiep] 
 ADD CONSTRAINT [PK_LichSuTotNghiep]
	PRIMARY KEY CLUSTERED ([MaHV] ASC,[MaChungChi] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_LichSuTotNghiep_ChungChi] 
 ON [LichSuTotNghiep] ([MaChungChi] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_LichSuTotNghiep_HocVien] 
 ON [LichSuTotNghiep] ([MaHV] ASC)
GO

ALTER TABLE [Lop] 
 ADD CONSTRAINT [PK_Lop]
	PRIMARY KEY CLUSTERED ([MaLop] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Lop_MonHoc] 
 ON [Lop] ([MaMH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Lop_NhanVien] 
 ON [Lop] ([MaNV] ASC)
GO

ALTER TABLE [MonHoc] 
 ADD CONSTRAINT [PK_MonHoc]
	PRIMARY KEY CLUSTERED ([MaMH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_MonHoc_NhomMonHoc] 
 ON [MonHoc] ([MaNhomMH] ASC)
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [PK_NhanVien]
	PRIMARY KEY CLUSTERED ([MaNV] ASC)
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [Uni_NV_CCCD] UNIQUE NONCLUSTERED ([CCCD] ASC)
GO

ALTER TABLE [NhomMonHoc] 
 ADD CONSTRAINT [PK_NhomMonHoc]
	PRIMARY KEY CLUSTERED ([MaNhomMH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_NhomMonHoc_ChungChi] 
 ON [NhomMonHoc] ([MaChungChi] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [DangKy] ADD CONSTRAINT [FK_DangKy_HoaDon]
	FOREIGN KEY ([MaHD]) REFERENCES [HoaDon] ([MaHD]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DangKy] ADD CONSTRAINT [FK_DangKy_HocVien]
	FOREIGN KEY ([MaHV]) REFERENCES [HocVien] ([MaHV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DangKy] ADD CONSTRAINT [FK_DangKy_Lop]
	FOREIGN KEY ([MaLop]) REFERENCES [Lop] ([MaLop]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDon] ADD CONSTRAINT [FK_HoaDon_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichSuThi] ADD CONSTRAINT [FK_LichSuThi_DangKy]
	FOREIGN KEY ([MaHV],[MaLop]) REFERENCES [DangKy] ([MaHV],[MaLop]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichSuTotNghiep] ADD CONSTRAINT [FK_LichSuTotNghiep_ChungChi]
	FOREIGN KEY ([MaChungChi]) REFERENCES [ChungChi] ([MaChungChi]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichSuTotNghiep] ADD CONSTRAINT [FK_LichSuTotNghiep_HocVien]
	FOREIGN KEY ([MaHV]) REFERENCES [HocVien] ([MaHV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Lop] ADD CONSTRAINT [FK_Lop_MonHoc]
	FOREIGN KEY ([MaMH]) REFERENCES [MonHoc] ([MaMH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Lop] ADD CONSTRAINT [FK_Lop_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [MonHoc] ADD CONSTRAINT [FK_MonHoc_NhomMonHoc]
	FOREIGN KEY ([MaNhomMH]) REFERENCES [NhomMonHoc] ([MaNhomMH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhomMonHoc] ADD CONSTRAINT [FK_NhomMonHoc_ChungChi]
	FOREIGN KEY ([MaChungChi]) REFERENCES [ChungChi] ([MaChungChi]) ON DELETE No Action ON UPDATE No Action
GO
